[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vv-gms"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Daniel Aucatoma", email = "d4n13l.4lf4@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "click==8.3.0",
    "dacite==1.9.2",
    "pydash==8.0.5"
]

[project.scripts]
gms-cli = "vv_gms.main:shell"

[project.urls]
Documentation = "https://github.com/d4n13l-4lf4/vv-gms#readme"
Issues = "https://github.com/d4n13l-4lf4/vv-gms/issues"
Source = "https://github.com/d4n13l-4lf4/vv-gms"

[tool.hatch.version]
path = "src/vv_gms/__about__.py"

# Environments
[tool.hatch.envs.build]
dependencies = [
    "pyinstaller==6.16.0"
]

[tool.hatch.envs.build.scripts]
package = "pyinstaller src/vv_gms/main.py {args}"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/vv_gms tests}"

[tool.hatch.envs.hatch-test]
extra-dependencies = [
    "PyHamcrest==2.1.0",
    "pytest",
    "pytest-cov",
    "pytest-subtests"
]

[tool.hatch.envs.hatch-test.scripts]
run = "pytest{env:HATCH_TEST_ARGS}: {args} -v --cov --cov-append --cov-report=term-missing"
run-cov = "coverage erase && coverage run -m pytest{env:HATCH_TEST_ARGS:} -v {args}"
cov-combine = "coverage combine"
cov-report = "coverage report && coverage xml && coverage html"

[tool.hatch.envs.dev]
from = "default"
dependencies = [
    "PyHamcrest==2.1.0",
    "pytest",
    "pytest-cov"
]

[tool.coverage.run]
source_pkgs = ["vv_gms"]
branch = true
parallel = true
omit = [
  "src/vv_gms/__about__.py",
  "**/__init__.py"
]

[tool.coverage.paths]
vv_gms = ["src/vv_gms", "*/vv-gms/src/vv_gms"]
tests = ["tests", "*/vv-gms/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]